# ML prediction Model :  using K-Fold Cross Validation


## Figuring out the best prediction model using cross validation method

In [4]:
#Importing the libraries numpy ,Logistic Regression, SVM , RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np


In [5]:
#Importing the 'Digits' dataset from  SKlearn library and loaded it into digits 
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()


In [3]:
#splitting the data into train test sets 
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(digits.data,digits.target,test_size=0.3)

### Using "Logistic Regression Algorithm"

In [9]:
lr = LogisticRegression()
lr.fit(X_train,Y_train)                          #traing the machine with these parts of data sets
lr.score ( X_test, Y_test)                       #checking the performance of the model


C:\Users\user\Documents\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9703703703703703

### Using "Support Vector Machine Algorithm"

In [10]:
svm = SVC()
svm.fit(X_train,Y_train)
svm.score(X_test,Y_test)

0.9944444444444445

### Using "Random Forest Algorithm"

In [11]:
rf = RandomForestClassifier()
rf.fit(X_train,Y_train)
rf.score(X_test,Y_test)

0.9740740740740741

### Using Cross Validation Method , Checking the performance of the model

In [12]:
from sklearn.model_selection import cross_val_score

In [13]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\user\Documents\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\user\Documents\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regr

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [17]:
algo1 = cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\user\Documents\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\user\Documents\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regr

In [19]:
algo1 = algo1.mean()
algo1

0.9137650882079852

In [14]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [23]:
algo2 = cross_val_score(SVC(),digits.data,digits.target)


In [25]:
algo2 = algo2.mean()
algo2 

0.9632838130609718

In [32]:
cross_val_score(RandomForestClassifier(n_estimators = 40),digits.data,digits.target)

array([0.93333333, 0.90555556, 0.95821727, 0.95264624, 0.94428969])

In [33]:
algo3 = cross_val_score(RandomForestClassifier(n_estimators = 40),digits.data,digits.target)

In [34]:
algo3 = algo3.mean()
algo3

0.9360213556174559

### By the use of Cross Validation Method we can get the results of each algorithm 
### By taking mean of each result we can direct compare the most efficient algorithm for this model